TAG: 'Prediction'

GPUS: [0,1,2,3,4,5,6,7]

BATCHSIZE: 2
PRECISION: 16
EPOCHS: 20

N_WORKERS: 8

DATASET:
  VERSION: 'trainval'

TIME_RECEPTIVE_FIELD: 3
N_FUTURE_FRAMES: 4

LIFT:
  GT_DEPTH: True

MODEL:
  ENCODER:
    NAME: 'efficientnet-b4'
    USE_DEPTH_DISTRIBUTION: True
  TEMPORAL_MODEL:
    NAME: 'temporal_block'
    INPUT_EGOPOSE: True
  BN_MOMENTUM: 0.05

SEMANTIC_SEG:
  PEDESTRIAN:
    ENABLED: False
  HDMAP:
    ENABLED: False

INSTANCE_SEG:
  ENABLED: False

INSTANCE_FLOW:
  ENABLED: False

PROBABILISTIC:
  ENABLED: False
  METHOD: 'GAUSSIAN'

PLANNING:
  ENABLED: False

FUTURE_DISCOUNT: 0.95

OPTIMIZER:
  LR: 2e-4


PRETRAINED:
   LOAD_WEIGHTS: False
